apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        imagePullPolicy: IfNotPresent
        image:  pibopibopibo/jenkins:auth
        ports:
          - containerPort: 80
            name: http-web-svc
        
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 80
    targetPort: http-web-svc
